version: '3'
services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    ports:
     - "9000:8080"
  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    ports:
     - "8000:8080"
