version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        type: consumer
    ports:
      - "9000:8080"
    links:
      - "rabbitmq:rabbitmq"
  producer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        type: producer
    ports:
      - "8000:8080"
    links:
      - "rabbitmq:rabbitmq"
